import { useState, useEffect } from 'react';
import { 
  CheckCircle2, Clock, Trash2, X, Edit, BarChart3, FileText, 
  Archive, Download, Filter, Calendar, TrendingUp, ShoppingBag, 
  Package, AlertTriangle, ChevronDown, Check, Save
} from 'lucide-react';
import { apiFetch } from '../../utils/api';
import { 
  ResponsiveContainer, LineChart, Line, BarChart, Bar, XAxis, YAxis, 
  CartesianGrid, Tooltip, Legend 
} from 'recharts';
import { exportToCSV, exportToExcel, exportToPDF } from '../../utils/exportUtils';

export default function AdminReports() {
  // Navigation / Tabs State
  const [activeTab, setActiveTab] = useState('generate'); // 'generate' or 'archive'
  
  // Archive List State
  const [archiveItems, setArchiveItems] = useState([]);
  const [archiveLoading, setArchiveLoading] = useState(true);
  const [showArchiveModal, setShowArchiveModal] = useState(false);
  const [editingArchiveId, setEditingArchiveId] = useState(null);
  const [archiveSearchTerm, setArchiveSearchTerm] = useState('');
  
  // Archive Modal Form Data
  const [archiveFormData, setArchiveFormData] = useState({
    reportName: '',
    category: 'Operational',
    status: 'Draft',
    createdBy: 'System Admin',
    fileUrl: ''
  });

  // Report Generator Filter State
  const [reportType, setReportType] = useState('Sales'); // 'Sales', 'Orders', 'Inventory'
  const [timeframe, setTimeframe] = useState('Monthly'); // 'Daily', 'Weekly', 'Monthly', 'Yearly', 'Custom'
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  
  // Generated Report Data & Visuals State
  const [generatedData, setGeneratedData] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [savingReport, setSavingReport] = useState(false);
  const [customReportName, setCustomReportName] = useState('');
  const [showSaveConfirmModal, setShowSaveConfirmModal] = useState(false);

  // Fetch Archive Reports
  const fetchArchiveItems = async () => {
    try {
      const data = await apiFetch('/reports');
      setArchiveItems(data);
    } catch (error) {
      console.error('Failed to fetch archived reports:', error);
    } finally {
      setArchiveLoading(false);
    }
  };

  useEffect(() => {
    fetchArchiveItems();
  }, []);

  // Handle Archive CRUDS
  const handleArchiveSubmit = async (e) => {
    e.preventDefault();
    try {
      if (editingArchiveId) {
        await apiFetch(`/reports/${editingArchiveId}`, {
          method: 'PUT',
          body: JSON.stringify(archiveFormData)
        });
      } else {
        await apiFetch('/reports', {
          method: 'POST',
          body: JSON.stringify(archiveFormData)
        });
      }
      setShowArchiveModal(false);
      setEditingArchiveId(null);
      setArchiveFormData({ reportName: '', category: 'Operational', status: 'Draft', createdBy: 'System Admin', fileUrl: '' });
      fetchArchiveItems();
    } catch (error) {
      alert(error.message);
    }
  };

  const handleArchiveEditClick = (item, e) => {
    e.stopPropagation();
    setArchiveFormData({
      reportName: item.reportName,
      category: item.category,
      status: item.status,
      createdBy: item.createdBy || 'System Admin',
      fileUrl: item.fileUrl || ''
    });
    setEditingArchiveId(item._id);
    setShowArchiveModal(true);
  };

  const handleArchiveDelete = async (id, e) => {
    e.stopPropagation();
    if (!window.confirm('Are you sure you want to delete this report metadata?')) return;
    
    try {
      await apiFetch(`/reports/${id}`, { method: 'DELETE' });
      fetchArchiveItems();
    } catch (error) {
      alert(error.message);
    }
  };

  const handleExportArchiveRowCSV = (report, e) => {
    e.stopPropagation();
    const headers = ['Report Name', 'Category', 'Status', 'Generated By', 'Date'];
    const keys = ['reportName', 'category', 'status', 'createdBy', 'date'];
    
    // Convert date for export compatibility
    const row = {
      ...report,
      date: report.date ? new Date(report.date).toLocaleDateString() : new Date(report.createdAt).toLocaleDateString()
    };

    exportToCSV([row], headers, keys, `historical_${report.reportName.replace(/\s+/g, '_')}`);
  };

  // Archive filtering
  const filteredArchiveItems = archiveItems.filter(i => 
    i.reportName.toLowerCase().includes(archiveSearchTerm.toLowerCase()) || 
    i.category.toLowerCase().includes(archiveSearchTerm.toLowerCase())
  );

  // Generate Real-time Report Engine
  const handleGenerateReport = async () => {
    setGenerating(true);
    try {
      const now = new Date();
      let filterStart = new Date();
      
      // Compute start date based on filter
      if (timeframe === 'Daily') {
        filterStart.setHours(0,0,0,0);
      } else if (timeframe === 'Weekly') {
        filterStart.setDate(now.getDate() - 7);
      } else if (timeframe === 'Monthly') {
        filterStart.setDate(now.getDate() - 30);
      } else if (timeframe === 'Yearly') {
        filterStart.setDate(now.getDate() - 365);
      } else if (timeframe === 'Custom' && startDate) {
        filterStart = new Date(startDate);
      } else {
        filterStart.setDate(now.getDate() - 30); // fallback 30 days
      }

      let filterEnd = new Date();
      if (timeframe === 'Custom' && endDate) {
        filterEnd = new Date(endDate);
        filterEnd.setHours(23,59,59,999);
      }

      if (reportType === 'Sales') {
        // Fetch SalesOrders
        const allSales = await apiFetch('/sales-orders').catch(() => []);
        
        // Filter by date range
        const filteredSales = allSales.filter(item => {
          const orderDate = new Date(item.orderDate || item.createdAt);
          return orderDate >= filterStart && orderDate <= filterEnd;
        });

        // Compute KPIs
        const totalRevenue = filteredSales.reduce((sum, o) => sum + (o.totalAmount || 0), 0);
        const orderCount = filteredSales.length;
        const avgOrderVal = orderCount > 0 ? (totalRevenue / orderCount) : 0;
        const totalUnits = filteredSales.reduce((sum, o) => sum + (o.quantity || 0), 0);

        // Compute Chart Data (group by date)
        const groupedMap = {};
        filteredSales.forEach(s => {
          const dateLabel = new Date(s.orderDate || s.createdAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
          groupedMap[dateLabel] = (groupedMap[dateLabel] || 0) + s.totalAmount;
        });

        const chartData = Object.keys(groupedMap).map(key => ({
          date: key,
          Sales: groupedMap[key]
        })).sort((a,b) => new Date(a.date) - new Date(b.date));

        setGeneratedData({
          type: 'Sales',
          timeframe,
          start: filterStart,
          end: filterEnd,
          items: filteredSales,
          kpis: { totalRevenue, orderCount, avgOrderVal, totalUnits },
          chartData: chartData.length > 0 ? chartData : [{ date: 'No Data', Sales: 0 }],
          headers: ['Order Number', 'Date', 'Customer', 'Product', 'Quantity', 'Amount (₨)', 'Payment Status', 'Delivery Status'],
          keys: ['orderNumber', 'orderDateStr', 'customer', 'productName', 'quantity', 'totalAmount', 'paymentStatus', 'deliveryStatus']
        });
        setCustomReportName(`Sales Report (${timeframe} Audit) - ${now.toLocaleDateString()}`);

      } else if (reportType === 'Orders') {
        // Fetch OrderQuotes
        const allQuotes = await apiFetch('/orders').catch(() => []);

        // Filter by date
        const filteredQuotes = allQuotes.filter(item => {
          const qDate = new Date(item.createdAt);
          return qDate >= filterStart && qDate <= filterEnd;
        });

        // Compute KPIs
        const quoteCount = filteredQuotes.length;
        const totalEstValue = filteredQuotes.reduce((sum, q) => sum + (q.totalPrice || 0), 0);
        
        // Status counts
        const statusCounts = {};
        filteredQuotes.forEach(q => {
          statusCounts[q.status] = (statusCounts[q.status] || 0) + 1;
        });
        
        const delivered = statusCounts['Delivered'] || 0;
        const rejected = statusCounts['Rejected'] || 0;
        const activeRequests = quoteCount - (delivered + rejected);

        // Chart Data (Group by status)
        const chartData = Object.keys(statusCounts).map(status => ({
          name: status,
          Count: statusCounts[status]
        }));

        setGeneratedData({
          type: 'Orders',
          timeframe,
          start: filterStart,
          end: filterEnd,
          items: filteredQuotes,
          kpis: { quoteCount, totalEstValue, activeRequests, delivered },
          chartData: chartData.length > 0 ? chartData : [{ name: 'No Data', Count: 0 }],
          headers: ['Quote ID', 'Requested Date', 'Customer Name', 'Product', 'Quantity', 'Estimated Price (₨)', 'Status'],
          keys: ['_id', 'createdAtStr', 'contactPerson', 'product', 'quantity', 'totalPrice', 'status']
        });
        setCustomReportName(`Customer Requests Audit (${timeframe}) - ${now.toLocaleDateString()}`);

      } else if (reportType === 'Inventory') {
        // Fetch current inventories & raw materials
        const [inventories, rawMaterials] = await Promise.all([
          apiFetch('/inventory').catch(() => []),
          apiFetch('/raw-materials').catch(() => [])
        ]);

        // Compute KPIs
        const totalProducts = inventories.length;
        const totalRawMaterials = rawMaterials.length;
        
        // Count low stock items
        const lowStockProducts = inventories.filter(i => i.availableStock <= 5000).length; // assuming reorder limit is 5000 for bricks
        const lowStockRaw = rawMaterials.filter(r => r.stockQuantity <= r.reorderLevel).length;
        const totalLowStockAlerts = lowStockProducts + lowStockRaw;

        const totalStockUnits = inventories.reduce((sum, i) => sum + (i.totalStock || 0), 0);

        // Chart data
        const chartData = inventories.map(i => ({
          name: i.product,
          Available: i.availableStock || 0,
          Reserved: i.reservedStock || 0
        }));

        // Flatten data lists for report view
        const combinedStockItems = [
          ...inventories.map(i => ({
            name: i.product,
            type: 'Product Brick',
            stockQuantity: i.totalStock,
            reservedStock: i.reservedStock,
            availableStock: i.availableStock,
            status: i.availableStock <= 5000 ? 'Low Stock' : 'In Stock'
          })),
          ...rawMaterials.map(r => ({
            name: r.materialName,
            type: `Raw Material (${r.unit})`,
            stockQuantity: r.stockQuantity,
            reservedStock: 0,
            availableStock: r.stockQuantity,
            status: r.status
          }))
        ];

        setGeneratedData({
          type: 'Inventory',
          timeframe: 'Current Status',
          start: new Date(),
          end: new Date(),
          items: combinedStockItems,
          kpis: { totalProducts, totalRawMaterials, totalLowStockAlerts, totalStockUnits },
          chartData: chartData.length > 0 ? chartData : [{ name: 'No Products', Available: 0, Reserved: 0 }],
          headers: ['Item Name', 'Inventory Type', 'Total Quantity', 'Reserved Stock', 'Available Quantity', 'Stock Status'],
          keys: ['name', 'type', 'stockQuantity', 'reservedStock', 'availableStock', 'status']
        });
        setCustomReportName(`Inventory Status Audit - ${now.toLocaleDateString()}`);
      }
    } catch (err) {
      console.error(err);
      alert('Failed to generate report: ' + err.message);
    } finally {
      setGenerating(false);
    }
  };

  // Trigger initial report generation on mount or tab focus
  useEffect(() => {
    if (activeTab === 'generate' && !generatedData) {
      handleGenerateReport();
    }
  }, [activeTab]);

  // Export Dynamic Report Data
  const handleDynamicExport = (format) => {
    if (!generatedData) return;
    
    // Map items for safe exporting
    const exportItems = generatedData.items.map(item => {
      const row = { ...item };
      
      // Date formatting for export
      if (row.orderDate) row.orderDateStr = new Date(row.orderDate).toLocaleDateString();
      else if (row.createdAt) row.createdAtStr = new Date(row.createdAt).toLocaleDateString();
      
      return row;
    });

    const exportTitle = `${generatedData.type} Report - ${timeframe}`;
    const filename = `${generatedData.type.toLowerCase()}_report`;

    if (format === 'csv') {
      exportToCSV(exportItems, generatedData.headers, generatedData.keys, filename);
    } else if (format === 'excel') {
      exportToExcel(exportItems, generatedData.headers, generatedData.keys, filename);
    } else if (format === 'pdf') {
      exportToPDF(exportItems, generatedData.headers, generatedData.keys, exportTitle, filename);
    }
  };

  // Save Dynamic Report to Database Archive
  const handleSaveReportToArchive = async () => {
    if (!generatedData) return;
    setSavingReport(true);
    try {
      const newReportMeta = {
        reportName: customReportName || `${generatedData.type} Report Audit`,
        category: generatedData.type === 'Sales' ? 'Financial' : generatedData.type === 'Orders' ? 'Operational' : 'Inventory Ratios',
        status: 'Published',
        createdBy: 'System Admin',
        fileUrl: '', // metadata only
        date: new Date()
      };

      await apiFetch('/reports', {
        method: 'POST',
        body: JSON.stringify(newReportMeta)
      });
      
      setShowSaveConfirmModal(false);
      alert('Report saved to archive successfully!');
      fetchArchiveItems();
    } catch (err) {
      alert('Failed to save report: ' + err.message);
    } finally {
      setSavingReport(false);
    }
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8 relative">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-2xl font-bold text-brown-900 mb-1">Generated Reports & Audits</h2>
          <p className="text-gray-500 text-sm">Review published financial ledgers, operational logs, yield audits, and download CSV spreadsheets</p>
        </div>
        <div className="flex bg-gray-100 p-1 rounded-xl shrink-0">
          <button 
            onClick={() => setActiveTab('generate')}
            className={`px-4 py-2 text-xs font-bold rounded-lg transition-all cursor-pointer ${activeTab === 'generate' ? 'bg-white text-brown-900 shadow-sm' : 'text-gray-400 hover:text-gray-600'}`}
          >
            <BarChart3 className="w-3.5 h-3.5 inline mr-1.5" />
            Generate Report
          </button>
          <button 
            onClick={() => setActiveTab('archive')}
            className={`px-4 py-2 text-xs font-bold rounded-lg transition-all cursor-pointer ${activeTab === 'archive' ? 'bg-white text-brown-900 shadow-sm' : 'text-gray-400 hover:text-gray-600'}`}
          >
            <Archive className="w-3.5 h-3.5 inline mr-1.5" />
            Report Archive ({archiveItems.length})
          </button>
        </div>
      </div>

      {activeTab === 'generate' ? (
        /* Generator Tab */
        <div className="space-y-8">
          
          {/* Filter Panel */}
          <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm flex flex-col md:flex-row items-end gap-4">
            <div className="w-full md:w-1/4">
              <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1.5">Report Category</label>
              <select
                value={reportType}
                onChange={e => setReportType(e.target.value)}
                className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-terracotta-500 bg-white text-brown-900 font-bold"
              >
                <option value="Sales">Sales & Revenue Report</option>
                <option value="Orders">Customer Requests & Orders</option>
                <option value="Inventory">Inventory Stock Ledger</option>
              </select>
            </div>

            {reportType !== 'Inventory' && (
              <div className="w-full md:w-1/4">
                <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1.5">Date Filter</label>
                <select
                  value={timeframe}
                  onChange={e => setTimeframe(e.target.value)}
                  className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-terracotta-500 bg-white text-brown-900 font-bold"
                >
                  <option value="Daily">Daily (Today)</option>
                  <option value="Weekly">Weekly (Last 7 Days)</option>
                  <option value="Monthly">Monthly (Last 30 Days)</option>
                  <option value="Yearly">Yearly (Last 365 Days)</option>
                  <option value="Custom">Custom Date Range</option>
                </select>
              </div>
            )}

            {reportType !== 'Inventory' && timeframe === 'Custom' && (
              <>
                <div className="w-full md:w-1/5">
                  <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1.5">Start Date</label>
                  <input 
                    type="date"
                    value={startDate}
                    onChange={e => setStartDate(e.target.value)}
                    className="w-full px-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-terracotta-500 text-brown-900 bg-white"
                  />
                </div>
                <div className="w-full md:w-1/5">
                  <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1.5">End Date</label>
                  <input 
                    type="date"
                    value={endDate}
                    onChange={e => setEndDate(e.target.value)}
                    className="w-full px-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-terracotta-500 text-brown-900 bg-white"
                  />
                </div>
              </>
            )}

            <button 
              onClick={handleGenerateReport}
              disabled={generating}
              className="bg-brown-900 text-white font-bold px-6 py-2.5 rounded-lg text-sm hover:bg-black transition-colors shrink-0 flex items-center gap-2 cursor-pointer disabled:opacity-50"
            >
              <Filter className="w-4 h-4 text-terracotta-400" />
              {generating ? 'Compiling...' : 'Generate Report'}
            </button>
          </div>

          {/* Report Content */}
          {generating ? (
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-16 text-center text-gray-400 font-bold">
              Fetching database ledgers and calculating ratios...
            </div>
          ) : generatedData ? (
            <div className="space-y-8 animate-fadeIn">
              
              {/* Export and Save Toolbar */}
              <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center bg-white p-4 rounded-xl border border-gray-100 shadow-sm gap-4">
                <div className="flex items-center gap-2">
                  <span className="w-2.5 h-2.5 bg-green-500 rounded-full animate-pulse"></span>
                  <p className="text-xs text-gray-500 font-bold">
                    Report Compiled: <span className="text-brown-900 font-black">{generatedData.type} Data ({generatedData.timeframe})</span>
                  </p>
                </div>
                <div className="flex gap-2.5">
                  <button 
                    onClick={() => handleDynamicExport('csv')}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold border border-gray-200 rounded-lg hover:border-terracotta-500 text-brown-900 bg-white transition-colors cursor-pointer"
                  >
                    <Download className="w-3.5 h-3.5 text-terracotta-600" /> CSV
                  </button>
                  <button 
                    onClick={() => handleDynamicExport('excel')}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold border border-gray-200 rounded-lg hover:border-terracotta-500 text-brown-900 bg-white transition-colors cursor-pointer"
                  >
                    <Download className="w-3.5 h-3.5 text-green-600" /> Excel
                  </button>
                  <button 
                    onClick={() => handleDynamicExport('pdf')}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold border border-gray-200 rounded-lg hover:border-terracotta-500 text-brown-900 bg-white transition-colors cursor-pointer"
                  >
                    <Download className="w-3.5 h-3.5 text-red-600" /> PDF
                  </button>
                  <button 
                    onClick={() => setShowSaveConfirmModal(true)}
                    className="flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-bold bg-terracotta-600 hover:bg-terracotta-700 text-white rounded-lg transition-colors cursor-pointer"
                  >
                    <Save className="w-3.5 h-3.5" /> Archive Report
                  </button>
                </div>
              </div>

              {/* Generated KPIs */}
              {generatedData.type === 'Sales' && (
                <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                  <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm">
                    <span className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Total Revenue</span>
                    <h3 className="text-xl font-bold text-brown-900 font-mono">₨ {generatedData.kpis.totalRevenue.toLocaleString()}</h3>
                  </div>
                  <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm">
                    <span className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Orders Dispatched</span>
                    <h3 className="text-xl font-bold text-brown-900">{generatedData.kpis.orderCount}</h3>
                  </div>
                  <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm">
                    <span className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Avg Order Value</span>
                    <h3 className="text-xl font-bold text-brown-900 font-mono">₨ {Math.round(generatedData.kpis.avgOrderVal).toLocaleString()}</h3>
                  </div>
                  <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm">
                    <span className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Total Units Sold</span>
                    <h3 className="text-xl font-bold text-brown-900">{generatedData.kpis.totalUnits.toLocaleString()} Bricks</h3>
                  </div>
                </div>
              )}

              {generatedData.type === 'Orders' && (
                <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                  <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm">
                    <span className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Total Quote Requests</span>
                    <h3 className="text-xl font-bold text-brown-900">{generatedData.kpis.quoteCount}</h3>
                  </div>
                  <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm">
                    <span className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Est. Gross Quote pipeline</span>
                    <h3 className="text-xl font-bold text-brown-900 font-mono">₨ {generatedData.kpis.totalEstValue.toLocaleString()}</h3>
                  </div>
                  <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm">
                    <span className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Pending Review</span>
                    <h3 className="text-xl font-bold text-brown-900">{generatedData.kpis.activeRequests}</h3>
                  </div>
                  <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm">
                    <span className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Converted / Delivered</span>
                    <h3 className="text-xl font-bold text-brown-900">{generatedData.kpis.delivered}</h3>
                  </div>
                </div>
              )}

              {generatedData.type === 'Inventory' && (
                <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                  <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm">
                    <span className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Manufactured Products</span>
                    <h3 className="text-xl font-bold text-brown-900">{generatedData.kpis.totalProducts} Items</h3>
                  </div>
                  <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm">
                    <span className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Raw Material SKUs</span>
                    <h3 className="text-xl font-bold text-brown-900">{generatedData.kpis.totalRawMaterials} Materials</h3>
                  </div>
                  <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm flex items-center justify-between">
                    <div>
                      <span className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Low Stock Alerts</span>
                      <h3 className={`text-xl font-bold ${generatedData.kpis.totalLowStockAlerts > 0 ? 'text-red-600' : 'text-brown-900'}`}>{generatedData.kpis.totalLowStockAlerts} Warnings</h3>
                    </div>
                    {generatedData.kpis.totalLowStockAlerts > 0 && <AlertTriangle className="w-6 h-6 text-red-500 animate-pulse shrink-0" />}
                  </div>
                  <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm">
                    <span className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Total Finished Inventory</span>
                    <h3 className="text-xl font-bold text-brown-900 font-mono">{generatedData.kpis.totalStockUnits.toLocaleString()} units</h3>
                  </div>
                </div>
              )}

              {/* Chart section */}
              <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm space-y-4">
                <div className="flex items-center gap-2">
                  <TrendingUp className="w-5 h-5 text-terracotta-600" />
                  <h3 className="text-sm font-black text-brown-900 uppercase tracking-wider">{generatedData.type} Trend Visualization</h3>
                </div>
                
                <div className="h-72 w-full">
                  <ResponsiveContainer width="100%" height="100%">
                    {generatedData.type === 'Sales' ? (
                      <LineChart data={generatedData.chartData}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#f3f4f6" />
                        <XAxis dataKey="date" stroke="#9ca3af" fontSize={10} fontStyle="bold" />
                        <YAxis stroke="#9ca3af" fontSize={10} fontStyle="bold" tickFormatter={(v) => `₨${v >= 1000 ? (v/1000) + 'k' : v}`} />
                        <Tooltip formatter={(value) => [`₨ ${Number(value).toLocaleString()}`, 'Revenue']} />
                        <Legend />
                        <Line type="monotone" dataKey="Sales" stroke="#c14618" strokeWidth={3} dot={{ r: 4 }} activeDot={{ r: 7 }} />
                      </LineChart>
                    ) : generatedData.type === 'Orders' ? (
                      <BarChart data={generatedData.chartData}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#f3f4f6" />
                        <XAxis dataKey="name" stroke="#9ca3af" fontSize={10} fontStyle="bold" />
                        <YAxis stroke="#9ca3af" fontSize={10} fontStyle="bold" />
                        <Tooltip />
                        <Legend />
                        <Bar dataKey="Count" fill="#c14618" radius={[6, 6, 0, 0]} />
                      </BarChart>
                    ) : (
                      <BarChart data={generatedData.chartData}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#f3f4f6" />
                        <XAxis dataKey="name" stroke="#9ca3af" fontSize={10} fontStyle="bold" />
                        <YAxis stroke="#9ca3af" fontSize={10} fontStyle="bold" tickFormatter={(v) => `${v >= 1000 ? (v/1000) + 'k' : v}`} />
                        <Tooltip />
                        <Legend />
                        <Bar dataKey="Available" fill="#16a34a" stackId="a" radius={[0, 0, 0, 0]} />
                        <Bar dataKey="Reserved" fill="#f97316" stackId="a" radius={[6, 6, 0, 0]} />
                      </BarChart>
                    )}
                  </ResponsiveContainer>
                </div>
              </div>

              {/* Data Table */}
              <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
                <div className="px-6 py-4 border-b border-gray-50 bg-gray-50/50">
                  <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest">Audited Records Listing</h4>
                </div>
                <div className="overflow-x-auto">
                  {generatedData.items.length === 0 ? (
                    <div className="p-12 text-center text-gray-400 italic">No records found within the requested timeframe.</div>
                  ) : (
                    <table className="w-full text-left text-xs whitespace-nowrap">
                      <thead className="bg-gray-50/50 text-gray-400 font-bold tracking-wider text-[10px] uppercase border-b border-gray-50">
                        <tr>
                          {generatedData.headers.map((h, i) => (
                            <th key={i} className="px-6 py-4">{h}</th>
                          ))}
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-50 font-medium text-gray-700">
                        {generatedData.items.map((row, idx) => (
                          <tr key={row._id || idx} className="hover:bg-gray-50/30 transition-colors">
                            {generatedData.type === 'Sales' && (
                              <>
                                <td className="px-6 py-4 font-bold text-brown-900">{row.orderNumber}</td>
                                <td className="px-6 py-4 text-gray-400">{new Date(row.orderDate || row.createdAt).toLocaleDateString()}</td>
                                <td className="px-6 py-4">{row.customer}</td>
                                <td className="px-6 py-4">{(row.products && row.products[0]?.productName) || 'Standard Brick'}</td>
                                <td className="px-6 py-4 font-bold text-brown-900">{row.quantity?.toLocaleString()}</td>
                                <td className="px-6 py-4 font-black font-mono text-brown-950">₨ {row.totalAmount?.toLocaleString()}</td>
                                <td className="px-6 py-4">
                                  <span className={`inline-block px-1.5 py-0.5 rounded text-[10px] font-bold ${row.paymentStatus === 'Paid' ? 'bg-green-50 text-green-700' : 'bg-orange-50 text-orange-700'}`}>
                                    {row.paymentStatus}
                                  </span>
                                </td>
                                <td className="px-6 py-4">
                                  <span className={`inline-block px-1.5 py-0.5 rounded text-[10px] font-bold ${row.deliveryStatus === 'Delivered' ? 'bg-green-50 text-green-700' : 'bg-yellow-50 text-yellow-700'}`}>
                                    {row.deliveryStatus}
                                  </span>
                                </td>
                              </>
                            )}

                            {generatedData.type === 'Orders' && (
                              <>
                                <td className="px-6 py-4 font-mono font-bold text-terracotta-600">REQ-{row._id.slice(-6).toUpperCase()}</td>
                                <td className="px-6 py-4 text-gray-400">{new Date(row.createdAt).toLocaleDateString()}</td>
                                <td className="px-6 py-4 font-bold text-brown-900">{row.contactPerson}</td>
                                <td className="px-6 py-4">{row.product}</td>
                                <td className="px-6 py-4 font-bold text-brown-900">{row.quantity}</td>
                                <td className="px-6 py-4 font-black font-mono text-brown-950">₨ {row.totalPrice?.toLocaleString()}</td>
                                <td className="px-6 py-4">
                                  <span className={`inline-block px-1.5 py-0.5 rounded text-[10px] font-bold ${row.status === 'Delivered' ? 'bg-green-50 text-green-700' : 'bg-yellow-50 text-yellow-700'}`}>
                                    {row.status}
                                  </span>
                                </td>
                              </>
                            )}

                            {generatedData.type === 'Inventory' && (
                              <>
                                <td className="px-6 py-4 font-bold text-brown-900">{row.name}</td>
                                <td className="px-6 py-4 text-gray-400 font-semibold">{row.type}</td>
                                <td className="px-6 py-4 font-bold font-mono text-brown-900">{row.stockQuantity?.toLocaleString()}</td>
                                <td className="px-6 py-4 font-mono text-gray-400">{row.reservedStock?.toLocaleString() || 0}</td>
                                <td className="px-6 py-4 font-bold font-mono text-green-600">{row.availableStock?.toLocaleString()}</td>
                                <td className="px-6 py-4">
                                  <span className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded font-bold
                                    ${row.status === 'In Stock' || row.status === 'Active' ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'}
                                  `}>
                                    <span className={`w-1 h-1 rounded-full ${row.status === 'In Stock' || row.status === 'Active' ? 'bg-green-500' : 'bg-red-500'}`}></span>
                                    {row.status}
                                  </span>
                                </td>
                              </>
                            )}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                </div>
              </div>

            </div>
          ) : (
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-16 text-center text-gray-500 font-bold">
              Please click "Generate Report" to fetch system audit logs.
            </div>
          )}

        </div>
      ) : (
        /* Archive List Tab */
        <div className="space-y-8 animate-fadeIn">
          
          {/* Header Action Bar */}
          <div className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm flex flex-col sm:flex-row justify-end items-center gap-4">
            <button 
              onClick={() => { 
                setEditingArchiveId(null); 
                setArchiveFormData({ reportName: '', category: 'Operational', status: 'Draft', createdBy: 'System Admin', fileUrl: '' }); 
                setShowArchiveModal(true); 
              }} 
              className="flex items-center gap-1.5 bg-terracotta-600 text-white px-4 py-2 rounded-lg text-xs font-semibold hover:bg-terracotta-700 transition-colors shadow-sm cursor-pointer"
            >
              <FileText className="w-3.5 h-3.5" /> Log Manual Report Entry
            </button>
          </div>

          {/* Table */}
          <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
            <div className="overflow-x-auto">
              {archiveLoading ? (
                <div className="p-8 text-center text-gray-500">Loading reports archive ledger...</div>
              ) : filteredArchiveItems.length === 0 ? (
                <div className="p-8 text-center text-gray-500">No archived reports found in registry.</div>
              ) : (
                <table className="w-full text-left text-sm whitespace-nowrap">
                  <thead className="text-gray-400 font-bold tracking-wider text-[11px] uppercase border-b border-gray-50">
                    <tr>
                      <th className="px-6 py-4">Report Description</th>
                      <th className="px-6 py-4">Category</th>
                      <th className="px-6 py-4">Generated By</th>
                      <th className="px-6 py-4">Date Issued</th>
                      <th className="px-6 py-4">Status</th>
                      <th className="px-6 py-4"></th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-50">
                    {filteredArchiveItems.map((item) => (
                      <tr key={item._id} className="hover:bg-gray-50/50 transition-colors group">
                        <td className="px-6 py-5">
                          <div className="flex items-center gap-3">
                            <div className="w-8 h-8 rounded-lg bg-gray-100 flex items-center justify-center text-gray-500 shrink-0">
                              <FileText className="w-4 h-4" />
                            </div>
                            <span className="font-bold text-brown-900 text-[15px] group-hover:text-terracotta-600 transition-colors">
                              {item.reportName}
                            </span>
                          </div>
                        </td>
                        <td className="px-6 py-5 text-gray-600 font-bold text-xs uppercase">
                          {item.category}
                        </td>
                        <td className="px-6 py-5 text-gray-600 font-semibold">
                          {item.createdBy}
                        </td>
                        <td className="px-6 py-5 text-gray-500 font-medium">
                          {item.date ? new Date(item.date).toLocaleDateString() : new Date(item.createdAt).toLocaleDateString()}
                        </td>
                        <td className="px-6 py-5">
                          <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded text-xs font-bold tracking-wide
                            ${item.status === 'Published' ? 'bg-green-50 text-green-700' : item.status === 'Draft' ? 'bg-yellow-50 text-yellow-700' : 'bg-gray-100 text-gray-500'}
                          `}>
                            <span className={`w-1.5 h-1.5 rounded-full ${item.status === 'Published' ? 'bg-green-500' : item.status === 'Draft' ? 'bg-yellow-500' : 'bg-gray-400'}`}></span>
                            {item.status}
                          </span>
                        </td>
                        <td className="px-6 py-5 text-right flex justify-end gap-2">
                           <button 
                             onClick={(e) => handleExportArchiveRowCSV(item, e)} 
                             className="text-terracotta-600 hover:text-white hover:bg-terracotta-600 bg-terracotta-50 p-1.5 rounded-lg border border-terracotta-100 transition-colors" 
                             title="Export Metadata Row (CSV)"
                           >
                              <Download className="w-4 h-4" />
                           </button>
                           <button 
                             onClick={(e) => handleArchiveEditClick(item, e)} 
                             className="text-blue-500 hover:text-white hover:bg-blue-500 p-1.5 rounded-lg border border-blue-100 transition-colors" 
                             title="Edit Details"
                           >
                              <Edit className="w-4 h-4" />
                           </button>
                           <button 
                             onClick={(e) => handleArchiveDelete(item._id, e)} 
                             className="text-red-500 hover:text-white hover:bg-red-500 p-1.5 rounded-lg border border-red-100 transition-colors" 
                             title="Delete"
                           >
                              <Trash2 className="w-4 h-4" />
                           </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          </div>

        </div>
      )}

      {/* Save Archive Report Confirm Dialog */}
      {showSaveConfirmModal && generatedData && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-md p-6">
            <div className="flex justify-between items-center mb-4 border-b border-gray-50 pb-2">
              <h3 className="text-base font-black text-brown-900">Archive Audit Report</h3>
              <button onClick={() => setShowSaveConfirmModal(false)} className="text-gray-400 hover:text-gray-600">
                <X className="w-4 h-4" />
              </button>
            </div>
            
            <div className="space-y-4 text-xs font-semibold text-gray-500">
              <p>This will save the metadata reference of the current generated query into the system's persistent Archive log history.</p>
              
              <div>
                <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Archive Entry Name</label>
                <input 
                  type="text" 
                  value={customReportName} 
                  onChange={e => setCustomReportName(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-200 rounded-lg text-brown-900 font-bold focus:outline-none focus:ring-1 focus:ring-terracotta-500" 
                />
              </div>

              <div className="pt-2 flex gap-3">
                <button 
                  onClick={handleSaveReportToArchive}
                  disabled={savingReport}
                  className="w-1/2 bg-terracotta-600 text-white font-bold py-2.5 rounded-lg hover:bg-terracotta-700 transition-colors flex items-center justify-center gap-1.5 cursor-pointer disabled:opacity-50"
                >
                  <Check className="w-4 h-4" /> {savingReport ? 'Saving...' : 'Confirm Save'}
                </button>
                <button 
                  onClick={() => setShowSaveConfirmModal(false)}
                  className="w-1/2 bg-gray-100 text-brown-900 font-bold py-2.5 rounded-lg hover:bg-gray-250 transition-colors cursor-pointer"
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Manual Report Metadata Create/Edit Modal */}
      {showArchiveModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-md p-6">
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-xl font-bold text-brown-900">{editingArchiveId ? 'Edit Report Meta' : 'Log New Report Entry'}</h3>
              <button onClick={() => setShowArchiveModal(false)} className="text-gray-400 hover:text-gray-600">
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <form onSubmit={handleArchiveSubmit} className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Report Title / Description</label>
                <input 
                  required 
                  value={archiveFormData.reportName} 
                  onChange={e => setArchiveFormData({...archiveFormData, reportName: e.target.value})} 
                  type="text" 
                  className="w-full px-3 py-2 border rounded-lg focus:ring-1 focus:ring-terracotta-500 outline-none text-brown-900" 
                  placeholder="Q1 Financial Audit Ledger" 
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Category</label>
                  <select 
                    value={archiveFormData.category} 
                    onChange={e => setArchiveFormData({...archiveFormData, category: e.target.value})} 
                    className="w-full px-3 py-2 border rounded-lg focus:ring-1 focus:ring-terracotta-500 outline-none bg-white text-brown-900"
                  >
                    <option>Operational</option>
                    <option>Financial</option>
                    <option>Inventory Ratios</option>
                    <option>HR & Labor</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Status</label>
                  <select 
                    value={archiveFormData.status} 
                    onChange={e => setArchiveFormData({...archiveFormData, status: e.target.value})} 
                    className="w-full px-3 py-2 border rounded-lg focus:ring-1 focus:ring-terracotta-500 outline-none bg-white text-brown-900"
                  >
                    <option>Draft</option>
                    <option>Published</option>
                    <option>Archived</option>
                  </select>
                </div>
              </div>
              <div>
                <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Created By</label>
                <input 
                  required 
                  value={archiveFormData.createdBy} 
                  onChange={e => setArchiveFormData({...archiveFormData, createdBy: e.target.value})} 
                  type="text" 
                  className="w-full px-3 py-2 border rounded-lg focus:ring-1 focus:ring-terracotta-500 outline-none text-brown-900" 
                  placeholder="System Admin" 
                />
              </div>
              <button type="submit" className="w-full bg-terracotta-600 text-white font-bold py-3 rounded-lg hover:bg-terracotta-700 transition-colors mt-6 cursor-pointer">
                {editingArchiveId ? 'Update Report' : 'Save Entry'}
              </button>
            </form>
          </div>
        </div>
      )}

    </div>
  );
}
